name: PMS CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create Frontend .env
        working-directory: ./frontend
        run: |
          cat > .env << EOF
          API_URL=http://localhost:${{ secrets.BACKEND_PORT }}
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          API_ID=${{ secrets.API_ID }}
          API_KEY=${{ secrets.API_KEY }}
          NEXT_PUBLIC_API_ID=${{ secrets.NEXT_PUBLIC_API_ID }}
          NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}
          NEXT_TELEMETRY_DISABLED=1
          EOF

      - name: Create Backend .env
        working-directory: ./backend
        run: |
          cat > .env << EOF
          PORT=${{ secrets.BACKEND_PORT }}
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_SECRET_KEY=${{ secrets.SUPABASE_SECRET_KEY }}
          API_ID=${{ secrets.API_ID }}
          API_KEY=${{ secrets.API_KEY }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          EOF

      - name: Build and Push Docker Images
        run: |
          docker compose build
          docker compose push

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd project-10xdev
            git checkout main
            git pull
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose up -d
