name: PMS CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Access server and Create & Run Docker Image
        env:
          SERVER_USER: ${{secrets.SERVER_USER}}
          SERVER_IP: ${{secrets.SERVER_IP}}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@SERVER_IP << EOF
            cd project-10xdev
            git checkout main
            git pull
            sudo docker compose build
            sudo docker compose down
            sudo docker compose up -d
          EOF
